spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: air-sphere-connect-back

  # Docker Compose pour développement local uniquement
  docker:
    compose:
      file: ../docker-compose.yml
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Configuration commune
server:
  port: 8080

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    root: INFO
    com.air-sphere-connect: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG