spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: air-sphere-connect-back

  # Docker Compose pour développement local uniquement
  docker:
    compose:
      enabled: false

  messages:
    basename: ValidationMessages
    encoding: UTF-8

  jackson:
    serialization:
          WRITE_DATES_AS_TIMESTAMPS: false


# Configuration commune
server:
  port: 8080

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    root: INFO
    com.air-sphere-connect: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

