services:
  # ==============================
  # BASE DE DONNÉES MARIADB
  # ==============================
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_CHARSET: ${DB_CHARSET}
      MYSQL_COLLATION: ${DB_COLLATION}

    ports:
      - "${DB_PORT}:3306"

    volumes:
      - ${DB_VOLUME_NAME}:/var/lib/mysql

    networks:
      - ${NETWORK_NAME}

    # ✅ Health check corrigé pour MariaDB
    healthcheck:
      test: [ "CMD", "mariadb", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}", "-e", "SELECT 1" ]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}

  # ==============================
  # MAILHOG
  # ==============================

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: unless-stopped

    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI

    networks:
      - ${NETWORK_NAME}

    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8025" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # ==============================
  # BACKEND SPRING BOOT
  # ==============================
  backend:
    build:
      context: ${BACKEND_CONTEXT}
      dockerfile: ${BACKEND_DOCKERFILE}

    container_name: ${BACKEND_CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env


    ports:
      - "8081:8080"
#      - "${DEBUG_PORT}:5005"

    depends_on:
      mariadb:
        condition: service_healthy

    networks:
      - ${NETWORK_NAME}

    # ✅ Health check backend (nécessite curl dans Dockerfile)
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}

  # ==============================
  # FRONTEND ANGULAR
  # ==============================
  frontend:
    build:
      context: ${FRONTEND_CONTEXT}
      dockerfile: ${FRONTEND_DOCKERFILE}

    container_name: ${FRONTEND_CONTAINER_NAME}
    restart: unless-stopped

    environment:
      API_URL: ${API_URL}
      NODE_ENV: ${NODE_ENV:-development}

    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

    depends_on:
      backend:
        condition: service_healthy

    networks:
      - ${NETWORK_NAME:-air-sphere-connect-network}

    # ✅ Health check avec curl (cohérent avec backend)
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4200 || exit 1"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: 3

# ==============================
# VOLUMES
# ==============================
volumes:
  air-sphere-connect_db_data:
    name: ${DB_VOLUME_NAME}
    driver: local

# ==============================
# NETWORKS
# ==============================
networks:
  air-sphere-connect-network:
    name: ${NETWORK_NAME}
    driver: bridge