# ==============================
# Configuration SonarQube Frontend Angular
# ==============================

# Identifiant unique du projet
sonar.projectKey=air-sphere-connect-frontend
sonar.projectName=AirSphere Connect - Frontend
sonar.projectVersion=1.0.0

# Encodage des fichiers sources
sonar.sourceEncoding=UTF-8

# Répertoires source et tests
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/documentation/**,**/*.js,**/*.d.ts

# TypeScript/JavaScript
sonar.typescript.lcov.reportPaths=coverage/air-sphere-connect-front/lcov.info

# Niveau de log
sonar.log.level=INFO

# URL du serveur SonarQube (localhost en dev)
sonar.host.url=http://localhost:9000

# Token d'authentification ( g�n�rer depuis SonarQube UI)
# sonar.token=YOUR_SONARQUBE_TOKEN

# Règles SonarQube à ignorer (faux positifs)
sonar.issue.ignore.multicriteria=e1,e2

# S6840: Désactiver pour les fichiers HTML car nos composants Angular propagent correctement l'attribut autocomplete
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S6840
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.html

# S4662: Désactiver pour styles.scss car il contient des propriétés DaisyUI personnalisées valides
sonar.issue.ignore.multicriteria.e2.ruleKey=css:S4662
sonar.issue.ignore.multicriteria.e2.resourceKey=**/styles.scss

# Règles SonarQube à ignorer (browser incompatibility)
sonar.issue.ignore.multicriteria=e3

# S7785: Ne peut pas être résolu car pas compatibles sur les autres navigateurs
sonar.issue.ignore.multicriteria.e3.ruleKey=typescript:S7785
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*.ts

# Ignorer les @plugin, @theme, @layer, etc. utilisés par Tailwind / DaisyUI
sonar.css.ignoreAtRules=plugin,theme,layer,variants,utilities,tailwind,apply,config
